# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\YOLO\yolov7-main-zyy\UI\main_grade.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 899)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/png/icon/上海大学002.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(400, 45))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: #000000;  /* 已更改为黑色 */\n"
"    font-size: 24px;  /* 字体大小已恢复为 24px */\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    qproperty-alignment: AlignCenter;\n"
"    border: 1px solid #4CAF50;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    background-color: #D3D3D3;\n"
"}\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.minButton = QtWidgets.QPushButton(self.centralwidget)
        self.minButton.setEnabled(True)
        self.minButton.setMinimumSize(QtCore.QSize(50, 28))
        self.minButton.setMaximumSize(QtCore.QSize(50, 28))
        self.minButton.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* 使用白色背景 */\n"
"    color: white; /* 使用白色文字，与白色背景形成对比 */\n"
"}\n"
"\n"
"QPushButton::focus {\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 255); /* 当鼠标悬停时，使按钮变得稍微深色，提供视觉反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 100, 255); /* 按钮被按下时，使按钮变得稍微浅色，提供视觉反馈 */\n"
"}\n"
"")
        self.minButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/png/icon/最小化_黑色.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon)
        self.minButton.setObjectName("minButton")
        self.horizontalLayout.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(self.centralwidget)
        self.maxButton.setMinimumSize(QtCore.QSize(50, 28))
        self.maxButton.setMaximumSize(QtCore.QSize(50, 28))
        self.maxButton.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* 使用白色背景 */\n"
"    color: white; /* 使用白色文字，与白色背景形成对比 */\n"
"}\n"
"\n"
"QPushButton::focus {\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 255); /* 当鼠标悬停时，使按钮变得稍微深色，提供视觉反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 100, 255); /* 按钮被按下时，使按钮变得稍微浅色，提供视觉反馈 */\n"
"}\n"
"")
        self.maxButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/png/icon/正方形_黑色.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxButton.setIcon(icon1)
        self.maxButton.setObjectName("maxButton")
        self.horizontalLayout.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setMinimumSize(QtCore.QSize(50, 28))
        self.closeButton.setMaximumSize(QtCore.QSize(50, 28))
        self.closeButton.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: #FFFFFF; /* 使用白色背景 */\n"
"    color: white; /* 使用白色文字，与白色背景形成对比 */\n"
"}\n"
"\n"
"QPushButton::focus {\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    background-color: rgba(60, 60, 60, 255); /* 当鼠标悬停时，使按钮变得稍微深色，提供视觉反馈 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(100, 100, 100, 255); /* 按钮被按下时，使按钮变得稍微浅色，提供视觉反馈 */\n"
"}\n"
"")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/png/icon/关闭_黑色.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 500))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setEnabled(True)
        self.comboBox.setMinimumSize(QtCore.QSize(50, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_7.addWidget(self.comboBox, 0, 0, 1, 1)
        self.file = QtWidgets.QPushButton(self.groupBox_2)
        self.file.setMinimumSize(QtCore.QSize(50, 30))
        self.file.setMaximumSize(QtCore.QSize(250, 30))
        self.file.setIconSize(QtCore.QSize(20, 20))
        self.file.setObjectName("file")
        self.gridLayout_7.addWidget(self.file, 1, 0, 1, 1)
        self.camera = QtWidgets.QPushButton(self.groupBox_2)
        self.camera.setMinimumSize(QtCore.QSize(50, 30))
        self.camera.setMaximumSize(QtCore.QSize(250, 30))
        self.camera.setObjectName("camera")
        self.gridLayout_7.addWidget(self.camera, 2, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 500))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(25, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.iouSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.iouSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.iouSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.iouSpinBox.setFont(font)
        self.iouSpinBox.setStyleSheet("")
        self.iouSpinBox.setMaximum(1.0)
        self.iouSpinBox.setSingleStep(0.01)
        self.iouSpinBox.setProperty("value", 0.45)
        self.iouSpinBox.setObjectName("iouSpinBox")
        self.horizontalLayout_3.addWidget(self.iouSpinBox)
        self.iouSlider = QtWidgets.QSlider(self.groupBox)
        self.iouSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.iouSlider.setStyleSheet("")
        self.iouSlider.setMaximum(100)
        self.iouSlider.setProperty("value", 45)
        self.iouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider.setObjectName("iouSlider")
        self.horizontalLayout_3.addWidget(self.iouSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(45, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.confSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.confSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.confSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.confSpinBox.setFont(font)
        self.confSpinBox.setMaximum(1.0)
        self.confSpinBox.setSingleStep(0.01)
        self.confSpinBox.setProperty("value", 0.25)
        self.confSpinBox.setObjectName("confSpinBox")
        self.horizontalLayout_4.addWidget(self.confSpinBox)
        self.confSlider = QtWidgets.QSlider(self.groupBox)
        self.confSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.confSlider.setMaximum(100)
        self.confSlider.setProperty("value", 25)
        self.confSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider.setObjectName("confSlider")
        self.horizontalLayout_4.addWidget(self.confSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_6.addWidget(self.checkBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rateSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.rateSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.rateSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.rateSpinBox.setFont(font)
        self.rateSpinBox.setDecimals(2)
        self.rateSpinBox.setMinimum(1.0)
        self.rateSpinBox.setMaximum(20.0)
        self.rateSpinBox.setSingleStep(1.0)
        self.rateSpinBox.setObjectName("rateSpinBox")
        self.horizontalLayout_5.addWidget(self.rateSpinBox)
        self.rateSlider = QtWidgets.QSlider(self.groupBox)
        self.rateSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.rateSlider.setMaximum(20)
        self.rateSlider.setPageStep(1)
        self.rateSlider.setProperty("value", 1)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setObjectName("rateSlider")
        self.horizontalLayout_5.addWidget(self.rateSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(350, 200))
        self.groupBox_4.setMaximumSize(QtCore.QSize(400000, 500))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.statistic_label = QtWidgets.QTextBrowser(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.statistic_label.setFont(font)
        self.statistic_label.setObjectName("statistic_label")
        self.gridLayout.addWidget(self.statistic_label, 1, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 600))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.StopDet = QtWidgets.QPushButton(self.groupBox_3)
        self.StopDet.setMinimumSize(QtCore.QSize(50, 30))
        self.StopDet.setMaximumSize(QtCore.QSize(250, 30))
        self.StopDet.setAutoExclusive(False)
        self.StopDet.setObjectName("StopDet")
        self.gridLayout_2.addWidget(self.StopDet, 2, 0, 1, 1)
        self.BeginDet = QtWidgets.QPushButton(self.groupBox_3)
        self.BeginDet.setMinimumSize(QtCore.QSize(50, 30))
        self.BeginDet.setMaximumSize(QtCore.QSize(250, 30))
        self.BeginDet.setIconSize(QtCore.QSize(30, 30))
        self.BeginDet.setCheckable(True)
        self.BeginDet.setObjectName("BeginDet")
        self.gridLayout_2.addWidget(self.BeginDet, 1, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMinimumSize(QtCore.QSize(400, 200))
        self.groupBox_6.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setMinimumSize(QtCore.QSize(45, 20))
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.guojingSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.guojingSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.guojingSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.guojingSpinBox.setFont(font)
        self.guojingSpinBox.setMaximum(1.0)
        self.guojingSpinBox.setSingleStep(0.01)
        self.guojingSpinBox.setProperty("value", 0.25)
        self.guojingSpinBox.setObjectName("guojingSpinBox")
        self.horizontalLayout_22.addWidget(self.guojingSpinBox)
        self.guojingSlider = QtWidgets.QSlider(self.groupBox_6)
        self.guojingSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.guojingSlider.setMaximum(100)
        self.guojingSlider.setProperty("value", 25)
        self.guojingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.guojingSlider.setObjectName("guojingSlider")
        self.horizontalLayout_22.addWidget(self.guojingSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setMinimumSize(QtCore.QSize(45, 20))
        self.label_17.setObjectName("label_17")
        self.verticalLayout_3.addWidget(self.label_17)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.yanseSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.yanseSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.yanseSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.yanseSpinBox.setFont(font)
        self.yanseSpinBox.setMaximum(1.0)
        self.yanseSpinBox.setSingleStep(0.01)
        self.yanseSpinBox.setProperty("value", 0.25)
        self.yanseSpinBox.setObjectName("yanseSpinBox")
        self.horizontalLayout_23.addWidget(self.yanseSpinBox)
        self.yanseSlider = QtWidgets.QSlider(self.groupBox_6)
        self.yanseSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.yanseSlider.setMaximum(100)
        self.yanseSlider.setProperty("value", 25)
        self.yanseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yanseSlider.setObjectName("yanseSlider")
        self.horizontalLayout_23.addWidget(self.yanseSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setMinimumSize(QtCore.QSize(45, 20))
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.yuanxingduSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.yuanxingduSpinBox.setMinimumSize(QtCore.QSize(50, 25))
        self.yuanxingduSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.yuanxingduSpinBox.setFont(font)
        self.yuanxingduSpinBox.setMaximum(1.0)
        self.yuanxingduSpinBox.setSingleStep(0.01)
        self.yuanxingduSpinBox.setProperty("value", 0.25)
        self.yuanxingduSpinBox.setObjectName("yuanxingduSpinBox")
        self.horizontalLayout_24.addWidget(self.yuanxingduSpinBox)
        self.yuanxingduSlider = QtWidgets.QSlider(self.groupBox_6)
        self.yuanxingduSlider.setMinimumSize(QtCore.QSize(80, 0))
        self.yuanxingduSlider.setMaximum(100)
        self.yuanxingduSlider.setProperty("value", 25)
        self.yuanxingduSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yuanxingduSlider.setObjectName("yuanxingduSlider")
        self.horizontalLayout_24.addWidget(self.yuanxingduSlider)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_15.addWidget(self.groupBox_6)
        self.groupBox_17 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_17.setMinimumSize(QtCore.QSize(350, 200))
        self.groupBox_17.setMaximumSize(QtCore.QSize(40000, 600))
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.resultWidget = QtWidgets.QListWidget(self.groupBox_17)
        self.resultWidget.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.resultWidget.setFont(font)
        self.resultWidget.setObjectName("resultWidget")
        self.gridLayout_8.addWidget(self.resultWidget, 3, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.groupBox_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMinimumSize(QtCore.QSize(350, 350))
        self.groupBox_5.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.raw_video = QtWidgets.QLabel(self.groupBox_5)
        self.raw_video.setMinimumSize(QtCore.QSize(250, 300))
        self.raw_video.setStyleSheet("background-image: url(:/png/icon/纯白图片.png);")
        self.raw_video.setText("")
        self.raw_video.setObjectName("raw_video")
        self.gridLayout_4.addWidget(self.raw_video, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_5)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(350, 350))
        self.groupBox_8.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.out_video = QtWidgets.QLabel(self.groupBox_8)
        self.out_video.setMinimumSize(QtCore.QSize(300, 300))
        self.out_video.setStyleSheet("background-image: url(:/png/icon/纯白图片.png);")
        self.out_video.setText("")
        self.out_video.setObjectName("out_video")
        self.gridLayout_13.addWidget(self.out_video, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setMinimumSize(QtCore.QSize(350, 350))
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.splitter = QtWidgets.QSplitter(self.groupBox_7)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.gradeWidget = QtWidgets.QListWidget(self.splitter)
        self.gradeWidget.setMinimumSize(QtCore.QSize(250, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.gradeWidget.setFont(font)
        self.gradeWidget.setObjectName("gradeWidget")
        self.horizontalLayout_25.addWidget(self.splitter)
        self.horizontalLayout_8.addWidget(self.groupBox_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(3, 10)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "苹果视觉识别与分级软件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "开始阶段"))
        self.file.setText(_translate("MainWindow", "文件"))
        self.camera.setText(_translate("MainWindow", "摄像头"))
        self.groupBox.setTitle(_translate("MainWindow", "iou/conf"))
        self.label_2.setText(_translate("MainWindow", "IoU"))
        self.label_3.setText(_translate("MainWindow", "置信度"))
        self.label_5.setText(_translate("MainWindow", "帧间延迟"))
        self.checkBox.setText(_translate("MainWindow", "启用"))
        self.groupBox_4.setTitle(_translate("MainWindow", "状态显示"))
        self.statistic_label.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'AcadEref\';\"><br /></p></body></html>"))
        self.groupBox_3.setTitle(_translate("MainWindow", "启动与停止"))
        self.StopDet.setText(_translate("MainWindow", "停止检测与分级"))
        self.BeginDet.setText(_translate("MainWindow", "开始检测与分级"))
        self.groupBox_6.setTitle(_translate("MainWindow", "分级权重"))
        self.label_16.setText(_translate("MainWindow", "α-果径"))
        self.label_17.setText(_translate("MainWindow", "β-颜色"))
        self.label_20.setText(_translate("MainWindow", "γ-圆形度"))
        self.groupBox_17.setTitle(_translate("MainWindow", "识别统计"))
        self.groupBox_5.setTitle(_translate("MainWindow", "原图/原视频"))
        self.groupBox_8.setTitle(_translate("MainWindow", "结果展示"))
        self.groupBox_7.setTitle(_translate("MainWindow", "分级评分"))

# import img_rc
